-- =============================================================================
-- VFS SCHEMA
-- =============================================================================
--
-- Virtual File System tables and seed data.
-- Applied by VFS.init() after EMS core schema is loaded.
--
-- DEPENDENCIES
-- ============
-- Requires EMS core schema (entities, models, fields tables must exist).
-- Foreign keys reference entities.id.

-- =============================================================================
-- SEED DATA: ROOT ENTITY
-- =============================================================================
-- The root entity is the namespace origin. All paths start here.
-- WHY well-known UUID: Simplifies bootstrap, no discovery needed.

INSERT OR IGNORE INTO entities (id, model, parent, pathname) VALUES
    ('00000000-0000-0000-0000-000000000000', 'folder', NULL, '');

-- =============================================================================
-- SEED DATA: VFS SYSTEM MODELS
-- =============================================================================
-- Core VFS entity types. Their detail is in per-model tables, blob data
-- (if any) is stored separately in HAL block storage.

INSERT OR IGNORE INTO models (model_name, status, description, pathname) VALUES
    ('file', 'system', 'Regular file entity - has associated blob data', 'name'),
    ('folder', 'system', 'Directory entity - contains child entries', 'name'),
    ('device', 'system', 'Device node entity - kernel device interface', 'name'),
    ('proc', 'system', 'Process/virtual file entity - dynamic content', 'name'),
    ('link', 'system', 'Symbolic link entity - path redirection', 'name'),
    ('temp', 'system', 'Temporary file entity - SQL metadata + HAL blob', 'name');

-- =============================================================================
-- FILE TABLE (Detail)
-- =============================================================================
-- Regular file entities. Metadata here, blob content in HAL block storage.

CREATE TABLE IF NOT EXISTS file (
    -- Identity: FK to entities table
    id          TEXT PRIMARY KEY REFERENCES entities(id) ON DELETE CASCADE,
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now')),
    trashed_at  TEXT,
    expired_at  TEXT,

    -- File-specific fields
    owner       TEXT NOT NULL,
    data        TEXT,                -- UUID reference to blob in HAL block storage
    size        INTEGER DEFAULT 0,
    mimetype    TEXT,
    checksum    TEXT
);

-- Index for listing files by owner
CREATE INDEX IF NOT EXISTS idx_file_owner
    ON file(owner);

-- =============================================================================
-- FOLDER TABLE (Detail)
-- =============================================================================
-- Directory entities. No blob data - children computed via entities.parent.

CREATE TABLE IF NOT EXISTS folder (
    -- Identity: FK to entities table
    id          TEXT PRIMARY KEY REFERENCES entities(id) ON DELETE CASCADE,
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now')),
    trashed_at  TEXT,
    expired_at  TEXT,

    -- Folder-specific fields
    owner       TEXT NOT NULL
);

-- Index for listing folders by owner
CREATE INDEX IF NOT EXISTS idx_folder_owner
    ON folder(owner);

-- =============================================================================
-- DEVICE TABLE (Detail)
-- =============================================================================
-- Device node entities. Kernel-provided virtual files (/dev/console, etc.).

CREATE TABLE IF NOT EXISTS device (
    -- Identity: FK to entities table
    id          TEXT PRIMARY KEY REFERENCES entities(id) ON DELETE CASCADE,
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now')),
    trashed_at  TEXT,
    expired_at  TEXT,

    -- Device-specific fields
    owner       TEXT NOT NULL,
    driver      TEXT NOT NULL
);

-- =============================================================================
-- PROC TABLE (Detail)
-- =============================================================================
-- Process/virtual file entities. Dynamic content generated by handler.

CREATE TABLE IF NOT EXISTS proc (
    -- Identity: FK to entities table
    id          TEXT PRIMARY KEY REFERENCES entities(id) ON DELETE CASCADE,
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now')),
    trashed_at  TEXT,
    expired_at  TEXT,

    -- Proc-specific fields
    owner       TEXT NOT NULL,
    handler     TEXT NOT NULL
);

-- =============================================================================
-- LINK TABLE (Detail)
-- =============================================================================
-- Symbolic link entities. Redirect path resolution to another location.

CREATE TABLE IF NOT EXISTS link (
    -- Identity: FK to entities table
    id          TEXT PRIMARY KEY REFERENCES entities(id) ON DELETE CASCADE,
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now')),
    trashed_at  TEXT,
    expired_at  TEXT,

    -- Link-specific fields
    owner       TEXT NOT NULL,
    target      TEXT NOT NULL
);

-- =============================================================================
-- TEMP TABLE (Detail)
-- =============================================================================
-- Temporary file entities for /tmp filesystem.

CREATE TABLE IF NOT EXISTS temp (
    -- Identity: FK to entities table
    id          TEXT PRIMARY KEY REFERENCES entities(id) ON DELETE CASCADE,
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now')),
    trashed_at  TEXT,
    expired_at  TEXT,

    -- Temp-specific fields
    owner       TEXT NOT NULL,
    size        INTEGER DEFAULT 0,
    mimetype    TEXT
);

-- =============================================================================
-- SEED DATA: ROOT FOLDER DETAIL
-- =============================================================================

INSERT OR IGNORE INTO folder (id, owner) VALUES
    ('00000000-0000-0000-0000-000000000000', 'system');

-- =============================================================================
-- SEED DATA: FILE MODEL FIELDS
-- =============================================================================
-- Note: parent and name are in entities table, not here

INSERT OR IGNORE INTO fields (model_name, field_name, type, required, description) VALUES
    ('file', 'owner', 'uuid', 1, 'Owner user or process ID'),
    ('file', 'size', 'integer', 0, 'Blob size in bytes'),
    ('file', 'mimetype', 'text', 0, 'MIME type (e.g., application/pdf)'),
    ('file', 'checksum', 'text', 0, 'Content hash for integrity verification');

-- =============================================================================
-- SEED DATA: FOLDER MODEL FIELDS
-- =============================================================================

INSERT OR IGNORE INTO fields (model_name, field_name, type, required, description) VALUES
    ('folder', 'owner', 'uuid', 1, 'Owner user or process ID');

-- =============================================================================
-- SEED DATA: DEVICE MODEL FIELDS
-- =============================================================================

INSERT OR IGNORE INTO fields (model_name, field_name, type, required, description) VALUES
    ('device', 'owner', 'uuid', 1, 'Owner user or process ID'),
    ('device', 'driver', 'text', 1, 'Device driver identifier (e.g., hal:console)');

-- =============================================================================
-- SEED DATA: PROC MODEL FIELDS
-- =============================================================================

INSERT OR IGNORE INTO fields (model_name, field_name, type, required, description) VALUES
    ('proc', 'owner', 'uuid', 1, 'Owner user or process ID'),
    ('proc', 'handler', 'text', 1, 'Handler function identifier');

-- =============================================================================
-- SEED DATA: LINK MODEL FIELDS
-- =============================================================================

INSERT OR IGNORE INTO fields (model_name, field_name, type, required, description) VALUES
    ('link', 'owner', 'uuid', 1, 'Owner user or process ID'),
    ('link', 'target', 'text', 1, 'Target path (absolute or relative)');

-- =============================================================================
-- SEED DATA: TEMP MODEL FIELDS
-- =============================================================================

INSERT OR IGNORE INTO fields (model_name, field_name, type, required, description) VALUES
    ('temp', 'owner', 'text', 1, 'Owner process or user ID'),
    ('temp', 'size', 'integer', 0, 'Blob size in bytes'),
    ('temp', 'mimetype', 'text', 0, 'MIME type (e.g., application/octet-stream)');
